sandbox:
  username: synesthesia
  password: 0rangutan78!
  consumer_key: synesthesiax
  consumer_secret: 3a45edd22990b97a

production:
  username: user
  password: password
  consumer_key: key
  consumer_secret: secret
